[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.conf"
# Replace a3e9c13b-cc1f-40c9-b300-f8b4bfa96e49 with a secrets version id
keys = [
  "/confg_discog/app/app_username",
  "/confg_discog/app/app_password",
  "/confg_discog/app/app_url",
  "/confg_discog/app/api_token",

  "/confg_discog/platform/db_connection_string",
  "/confg_discog/platform/db_name",
  "/confg_discog/platform/redis_connection_string",
]
