[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.conf"
# Replace a3e9c13b-cc1f-40c9-b300-f8b4bfa96e49 with a secrets version id
keys = [
    "/someconfig_user",
    "/someconfig_url",
    "/aws/reference/secretsmanager/someconfig_password_1:a3e9c13b-cc1f-40c9-b300-f8b4bfa96e49",
]
