[template]
src = "myconfig.conf.tmpl"
dest = "/tmp/myconfig.conf"
# Replace a3e9c13b-cc1f-40c9-b300-f8b4bfa96e49 with a secrets version id
keys = [
  "/confg_discog/confg_discog/app_username",
  "/confg_discog/confg_discog/app_password",
  "/confg_discog/confg_discog/app_url",
# "/aws/reference/secretsmanager/someconfig_password_fc46f2",
]
